"""empty message

Revision ID: 9f1010473ebc
Revises: a71062eb342f
Create Date: 2023-12-12 12:54:12.280691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1010473ebc'
down_revision = 'a71062eb342f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useremail', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['useremail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('useremail')

    # ### end Alembic commands ###


